apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ft.app.name }}
  labels:
    app: {{ .Values.ft.app.name }}
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      app: {{ .Values.ft.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ft.app.name }}
    spec:
      containers:
      - name: {{ .Values.ft.app.name }}
        image: "{{ .Values.image.repo }}:{{ .Values.version }}"
        env:
        - name: PORT
          value: "80"
        - name: API_HOST
          value: "http://webflow-backend-svc:3000"
        ports:
        - containerPort: {{ .Values.port }}
