apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.ft.app.name }}-svc"
spec:
  selector:
    app: webflow-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}