apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.bc.app.name }}-svc"
spec:
  selector:
    app: {{ .Values.bc.app.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}